name: Distribution deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  docker-build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Client Docker image
        run: |
          docker build \
            -t ghcr.io/thetechnetwork/checkmate:frontend-dist \
            -f ./docker/dist/client.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate \
            .

      - name: Push Client Docker image
        run: docker push ghcr.io/thetechnetwork/checkmate:frontend-dist

  docker-build-and-push-server:
    needs: docker-build-and-push-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Server Docker image
        run: |
          docker build \
            -t ghcr.io/thetechnetwork/checkmate:backend-dist \
            -f ./docker/dist/server.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate \
            .

      - name: Push Server Docker image
        run: docker push ghcr.io/thetechnetwork/checkmate:backend-dist

      - name: Build Mongo Docker image
        run: |
          docker build \
            -t ghcr.io/thetechnetwork/checkmate:mongo-dist \
            -f ./docker/dist/mongoDB.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate \
            .

      - name: Push MongoDB Docker image
        run: docker push ghcr.io/thetechnetwork/checkmate:mongo-dist

      - name: Build Redis Docker image
        run: |
          docker build \
            -t ghcr.io/thetechnetwork/checkmate:redis-dist \
            -f ./docker/dist/redis.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate \
            .

      - name: Push Redis Docker image
        run: docker push ghcr.io/thetechnetwork/checkmate:redis-dist
