name: Distribution deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1  Check out your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2  Enable QEMU so an x86 runner can cross-compile arm64 layers
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3  Install Buildx (buildctl-based builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4  Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5  Build & push CLIENT image (frontend)
      - name: Build & push client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dist/client.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/thetechnetwork/checkmate:frontend-dist
          labels: |
            org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate

      # 6  Build & push SERVER image (backend)
      - name: Build & push server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dist/server.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/thetechnetwork/checkmate:backend-dist
          labels: |
            org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate

      # 7  Build & push MONGO image
      - name: Build & push mongo
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dist/mongoDB.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/thetechnetwork/checkmate:mongo-dist
          labels: |
            org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate

      # 8  Build & push REDIS image
      - name: Build & push redis
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dist/redis.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/thetechnetwork/checkmate:redis-dist
          labels: |
            org.opencontainers.image.source=https://github.com/thetechnetwork/checkmate
